{keys:[
	[showHelp, F1],
	[saveAs, F2, file],
	[findNext,F3, search],
	[reloadWithEncoding,F5, encoding],
	[moveLeft, LEFT, cursor],
	[moveRight, RIGHT, cursor],
	[moveUp, UP, cursor],
	[moveDown, DOWN, cursor],
	[moveHome, HOME, cursor],
	[moveEnd, END, cursor],
	[moveEnd, ctrl-ENTER, cursor],
	[movePageUp, PAGE_UP, cursor],
	[movePageDown, PAGE_DOWN, cursor],
	[copySelected, ctrl-C, edit],
	[paste, ctrl-V, edit],
	[cut, ctrl-X, edit],
	[selectAll, ctrl-A, edit],
	[deleteLine, ctrl-D, edit],
	[openFile, ctrl-O, file],
	[newPage, ctrl-N, ui],
	[newWindow, ctrl-M, ui],
	[save, ctrl-S, file],
	[gotoLine, ctrl-L, cursor],
	[undo, ctrl-Z, edit],
	[find, ctrl-F, search],
	[redo, ctrl-Y, edit],
	[closePage, ctrl-W, UI],
	[setEncoding, ctrl-E, encoding],
	[moveToHead, ctrl-PAGE_UP, cursor],
	[moveToTail, ctrl-PAGE_DOWN, cursor],
	[removeTralingSpace, ctrl-R, edit],
	[moveLeftWord, ctrl-LEFT, cursor],
	[moveRightWord, ctrl-RIGHT, cursor],
	[moveViewUp, ctrl-UP, cursor],
	[moveViewDown, ctrl-DOWN, cursor],
	[resetScale, ctrl-0, scale],
	[go, ctrl-1, ui, "goto file or page or set font"],
	[fileHistory, ctrl-H, etc],
	[print, ctrl-P, etc, "print page"],
	[pageList, ctrl-Q, page],
	[quickSwitchPage, ctrl-TAB, page],
	[indentLeft, alt-LEFT, edit],
	[indentRight, alt-RIGHT, edit],
	[rectangleMode, alt-BACK_SLASH, edit],
	[makeNoise, alt-N, etc],
	[switchLineSeperator, alt-S, edit2],
	[wrapLines, alt-W, edit2],
	[Javascript, alt-J, script],
	[moveLeftBig, alt-PAGE_UP, cursor],
	[moveRightBig, alt-PAGE_DOWN, cursor],
	[switchColorMode, alt-C, etc],
	[moveBetweenPair, alt-P, cursor, "work on {} [] () <>"],
	[launch, alt-L, etc, "use system laucher on file, url"],
	[execute, alt-E, etc, "execute on command line"],
	[hex, alt-H, etc, "show hex code for characters"],
	[listFonts, alt-F, ui, "after listed, use 'go' key to set font"],
]}
